### ISSUE TITLE
Buttons do not have an accessible name

### ISSUE THREAD

**Issue by saragreenlaw** [brandid/social-proof-slider#6]
![Screen Shot 2020-01-13 at 11 19 47 AM](https://user-images.githubusercontent.com/6663757/72273058-ad5d7980-35f7-11ea-8810-33bea1982ee5.png)

**Comment by alexmustin** [comment]
Ref:
[https://developers.google.com/web/tools/lighthouse/audits/button-name](https://developers.google.com/web/tools/lighthouse/audits/button-name)
